namespace ModernPosSystem.Helpers;

public static class AppSettingKeys
{
    public const string ForecastingProvider = "ForecastingProvider";
    public const string LoyaltyEarnRate = "LoyaltyEarnRate";
    public const string LoyaltyRedeemValue = "LoyaltyRedeemValue";
    public const string LoyaltyMinimumRedeemPoints = "LoyaltyMinimumRedeemPoints";
    public const string ForecastLastAutoGeneratedAtUtc = "ForecastLastAutoGeneratedAtUtc";
    public const string ForecastLastAutoGeneratedDateLocal = "ForecastLastAutoGeneratedDateLocal";
    public const string ForecastLastManualGeneratedAtUtc = "ForecastLastManualGeneratedAtUtc";
}
