namespace ModernPosSystem.ViewModels;

public class ForecastingPageViewModel
{
    public ForecastFilterViewModel Filter { get; set; } = new();

    public List<SummaryCardViewModel> Cards { get; set; } = [];

    public List<LookupOptionViewModel> StoreOptions { get; set; } = [];

    public List<LookupOptionViewModel> CategoryOptions { get; set; } = [];

    public List<LookupOptionViewModel> ProductOptions { get; set; } = [];

    public List<ForecastResultRowViewModel> Results { get; set; } = [];

    public List<ChartSeriesViewModel> TopDemandChart { get; set; } = [];

    public List<ChartSeriesViewModel> ReorderChart { get; set; } = [];

    public List<ChartSeriesViewModel> SlowMovingChart { get; set; } = [];

    public List<ChartSeriesViewModel> CategoryDemandChart { get; set; } = [];

    public string ServiceStatus { get; set; } = "Unknown";

    public bool ServiceHealthy { get; set; }

    public DateTime? LastGeneratedAt { get; set; }

    public DateTime? LastAutoGeneratedAt { get; set; }

    public DateTime? LastManualGeneratedAt { get; set; }

    public DateTime? NextScheduledRunAt { get; set; }

    public bool AutoRunEnabled { get; set; }
}

public class ForecastFilterViewModel
{
    public string StoreId { get; set; } = string.Empty;

    public DateTime ForecastDate { get; set; } = DateTime.UtcNow.Date;

    public string? ProductId { get; set; }

    public string? CategoryId { get; set; }

    public string? ReorderStatus { get; set; }

    public bool SlowMovingOnly { get; set; }
}

public class ForecastResultRowViewModel
{
    public string Id { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string ProductCode { get; set; } = string.Empty;

    public string CategoryName { get; set; } = string.Empty;

    public decimal CurrentStock { get; set; }

    public decimal PredictedNextDaySales { get; set; }

    public decimal PredictedNext7DaysTotal { get; set; }

    public decimal SafetyStock { get; set; }

    public decimal ReorderSuggestedQuantity { get; set; }

    public string ReorderStatus { get; set; } = string.Empty;

    public bool IsSlowMoving { get; set; }

    public string ConfidenceLabel { get; set; } = string.Empty;

    public DateTime ForecastGeneratedAt { get; set; }

    public List<string> Warnings { get; set; } = [];
}

public class ForecastDetailViewModel
{
    public string Id { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string ProductCode { get; set; } = string.Empty;

    public decimal CurrentStock { get; set; }

    public decimal AverageRecentDailySales { get; set; }

    public decimal PredictedNextDaySales { get; set; }

    public decimal PredictedNext7DaysTotal { get; set; }

    public decimal SafetyStock { get; set; }

    public decimal ReorderSuggestedQuantity { get; set; }

    public string ReorderStatus { get; set; } = string.Empty;

    public bool IsSlowMoving { get; set; }

    public string SlowMovingExplanation { get; set; } = string.Empty;

    public string ReorderExplanation { get; set; } = string.Empty;

    public string ConfidenceLabel { get; set; } = string.Empty;

    public int InputHistoryDays { get; set; }

    public string ForecastModelName { get; set; } = string.Empty;

    public string ForecastVersion { get; set; } = string.Empty;

    public DateTime ForecastGeneratedAt { get; set; }

    public List<ForecastDetailDailyItemViewModel> DailyForecasts { get; set; } = [];

    public List<string> Warnings { get; set; } = [];
}

public class ForecastDetailDailyItemViewModel
{
    public DateTime Date { get; set; }

    public decimal PredictedQuantity { get; set; }
}
